### ISSUE TITLE
[feature]: 탈퇴한 유저, 이용제한, 영구정지 당한 유저의 접근을 막는다.

### ISSUE THREAD

**Issue by kpeel5839** [YAPP-Github/24th-App-Team-1-BE#74]
### Epic/Story Ticket Number

None

### 작업 사항

기천짱 제가 생각한 방법은 현재 Security Utils로 유저를 다 찾아오고 있잖아요!
그러면 여기서 탈퇴한 유저, 이용제한, 영구정지 당한 유저인 경우 예외를 던지기만 하면 좋을 것 같아요!
기천짱 생각은 어떠신가요?

<img width="880" alt="image" src="https://github.com/user-attachments/assets/5c2663ce-b707-4fb6-a6cd-cfc4a4d32a54">

### Todo

- [x] 방어 로직 작성
- [x] 테스트 추가

**Comment by sectionr0** [comment]
조회 API도 다 사용가능하고, 탈퇴의 경우는 오프라인에서 얘기했듯이 필터에서 접근을 막으면 안될 것 같아요!

아니면 권한에 따라 API 사용할 수 있는걸 나누면 좋을 것 같네용
